<script lang="ts">
	import { user, userID, userProfileData } from '$lib/firebase/firebase';
	import { getDoc, getDocs, query, where, collection, writeBatch, doc, arrayUnion, increment, Timestamp } from 'firebase/firestore';
	import { db } from '$lib/firebase/firebase';
	import type { TeamDataSNH2023 } from '$lib/components/types/TeamData';
	import * as Table from '$lib/components/ui/table';
	import { Button } from '$lib/components/ui/custom_button';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import type { CertificateData, CertificateStaticData } from '$lib/components/types/CertificateData';

	let data: TeamDataSNH2023[] = [];
	let certificateDetails: CertificateStaticData = {
		certificateTitle: 'Certificate of Participation',
		version: '1',
		issueDate: Timestamp.now().toDate(),
		startDate: Timestamp.fromDate(new Date('2023-11-10')).toDate(),
		endDate: Timestamp.fromDate(new Date('2023-11-26')).toDate(),
		description: 'In an era driven by innovation, fostering creative thinking and problem-solving skills among the youth is paramount. Smart Nitte Hackathon (SNH) 2023 is an exciting event organized by TASC, department of AIML, NMAMIT which encourages college students to showcase their creativity and problem-solving skills.',
		occasion: 'hackathon',
		role: 'participant',
		event: 'snh2023',
		organization: 'TASC, Dept. of AI & ML, NMAMIT',
		organizationLogo: 'snh2023/tascLogo.png',
		issuerNames: ['Dr. Sharada U. Shenoy', 'Dr. Niranjan N. Chiplunkar'],
		issuerDesignations: ['HoD, Dept. of AI & ML', 'Principal, NMAMIT'],
		issuerSignatures: ['snh2023/hod.png', 'snh2023/principal.png']
	};

	async function getData() {
		const teamsRef = collection(db, 'snh2023final');
		let q = query(teamsRef, where('arrived', '==', true));
		const docSnapshot = await getDocs(q);
		const docs = docSnapshot.docs;
		data = docs.flatMap((doc) => doc.data()) as TeamDataSNH2023[];
		// console.log(data);
	}

	async function getDataWrapper() {
		if ($user && $userID && $userProfileData) {
			await getData();
		}
	}

	async function issueCertificate(i: number) {
		if (data[i].certificate === true) {
			alert('Certificate already issued!');
			return;
		}

		generateCertificate(data[i]);
	}

	async function sha256(message: string) {
		const msgBuffer = new TextEncoder().encode(message); // encode as UTF-8
		const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer);
		const hashArray = Array.from(new Uint8Array(hashBuffer));
		const hashHex = hashArray.map((b) => ('00' + b.toString(16)).slice(-2)).join('');
		//console.log(hashHex);
		return hashHex;
	}

	async function generateCertificate(team: TeamDataSNH2023) {
		for (let i = 0; i < team.members.length; i++) {
			if (team[team.members[i]].status === 'pending') {
				break;
			}

			const batch = writeBatch(db);
			const teamRef = doc(db, 'snh2023final', team.teamID);
			const userRef = doc(db, 'user', team.members[i]);

			const certificateData = {
				...certificateDetails,

				userID: team.members[i],
				name: team[team.members[i]].name,
				email: team[team.members[i]].email,
				usn: team[team.members[i]].usn,
				college: team.college,

				teamID: team.teamID,
				teamName: team.teamName
			};

			const hash = await sha256(JSON.stringify(certificateData));

			// const newCertificateRef = doc(collection(db, 'certificate'));
			const newCertificateRef = doc(db, 'certificate', hash.slice(0, 24));

			batch.set(newCertificateRef, {
				certificateID: newCertificateRef.id,
				...certificateData,
				hash: hash
			});

			let userID = team.members[i];
			batch.update(teamRef, {
				certificate: true,
				[userID]: {
					...team[team.members[i]],
					certificate: newCertificateRef.id
				}
			});

			batch.update(userRef, {
				achievements: arrayUnion(newCertificateRef.id),
				[newCertificateRef.id]: {
					certificateTitle: certificateDetails.certificateTitle,
					issueDate: Timestamp.now(),
					occasion: certificateDetails.occasion,
					role: certificateDetails.role,
					event: certificateDetails.event,
					organization: certificateDetails.organization,
					teamID: team.teamID,
					teamName: team.teamName
				}
			});

			await batch.commit();
			alert('Certificate issued to ' + team[team.members[i]].name);
		}
	}
</script>

<!-- 
<div class="flex w-full justify-center">
	<div class="flex w-full max-w-md flex-col gap-1.5">
		<Label class="pt-5">Certificate ID</Label>

		<Label class="pt-5" for="certificateTitle">Certificate Title</Label>
		<Input id="certificateTitle" type="text" bind:value={certificateDetails.certificateTitle} />
		<p class="text-sm text-muted-foreground">Enter the certificate title.</p>

		<Label class="pt-5" for="versionInput">Version</Label>
		<Input type="number" id="versionInput" bind:value={certificateDetails.version} />

		<Label class="pt-5" for="issueDateInput">Issue Date (autogenerated)</Label>

		<Label class="pt-5" for="startDateInput">Start Date</Label>
		<Input type="date" id="startDateInput" bind:value={certificateDetails.startDate} />

		<Label class="pt-5" for="endDateInput">End Date</Label>
		<Input type="date" id="endDateInput" bind:value={certificateDetails.endDate} />

		<Label class="pt-5" for="validityInput">Validity (in years)</Label>
		<Input type="number" id="validityInput" bind:value={certificateDetails.validity} />

		<Label class="pt-5" for="occasionInput">Occasion</Label>
		<Input type="text" id="occasionInput" bind:value={certificateDetails.occasion} />

		<Label class="pt-5" for="roleInput">Role</Label>
		<Input type="text" id="roleInput" bind:value={certificateDetails.role} />

		<Label class="pt-5" for="eventInput">Event (same as occasion in some cases)</Label>
		<Input type="text" id="eventInput" bind:value={certificateDetails.event} />

		<Label class="pt-5" for="organizationInput">Organization</Label>
		<Input type="text" id="organizationInput" placeholder="Name" bind:value={certificateDetails.organization} />
		<Input type="text" id="organizationLogoInput" placeholder="Logo" bind:value={certificateDetails.organizationLogo} />

		<Label class="pt-5" for="numIssuersInput">Number of Issuers</Label>
		<Input type="number" id="numIssuersInput" bind:value={certificateDetails.issuerNames.length} />

		{#each Array.from({ length: certificateDetails.issuerNames.length }) as _, i}
			<Label class="pt-5" for={'issuerNameInput' + i}>Issuer {i + 1}</Label>
			<Input type="text" id={'issuerNameInput' + i} placeholder="Name" bind:value={certificateDetails.issuerNames[i]} />
			<Input type="url" id={'issuerSignatureInput' + i} placeholder="Signature Link" bind:value={certificateDetails.issuerSignatures[i]} />
		{/each}
	</div>
</div> -->

<div class="flex flex-col items-center justify-center text-center">
	<Button on:click={getDataWrapper}>Query the Database</Button>
	<Table.Root>
		<Table.Header>
			<Table.Row>
				<Table.Head>S No.</Table.Head>
				<Table.Head>Team Name</Table.Head>
				<Table.Head class="text-center">Member Count</Table.Head>
				<Table.Head class="text-center">College</Table.Head>
				<Table.Head class="text-center">Arrived</Table.Head>

				<Table.Head>Leader Name</Table.Head>
				<Table.Head class="text-center">Leader Email</Table.Head>
				<Table.Head class="text-center">Team ID</Table.Head>
				<Table.Head class="text-center">Team Secret</Table.Head>

				{#each { length: 3 } as _, i}
					<Table.Head>Member {i + 1}</Table.Head>
					<Table.Head>Status</Table.Head>
				{/each}

				<Table.Head class="text-center">Certificate</Table.Head>
				<Table.Head class="text-center">Issue Certificate</Table.Head>
			</Table.Row>
		</Table.Header>

		<Table.Body>
			{#each data as team, i}
				<Table.Row class="text-center">
					<Table.Cell>{i + 1}</Table.Cell>
					<Table.Cell>{team.teamName}</Table.Cell>
					<Table.Cell>{team.memberCount}</Table.Cell>
					<Table.Cell class="text-center">{team.college}</Table.Cell>
					<Table.Cell class="text-center">{team.arrived ? 'Yes' : 'No'}</Table.Cell>

					<Table.Cell>{team.leaderName}</Table.Cell>
					<Table.Cell>{team.leaderEmail}</Table.Cell>
					<Table.Cell>{team.teamID}</Table.Cell>
					<Table.Cell>{team.teamSecret}</Table.Cell>

					{#each { length: 3 } as _, i}
						{#if team.members[i]}
							<Table.Cell>{team[team.members[i]].name}</Table.Cell>
							<Table.Cell>{team[team.members[i]].status}</Table.Cell>
						{:else}
							<Table.Cell>Na</Table.Cell>
							<Table.Cell>Na</Table.Cell>
						{/if}
					{/each}

					<Table.Cell>{team.certificate ? 'Yes' : 'No'}</Table.Cell>
					<Table.Cell>
						<Button
							on:click={() => {
								issueCertificate(i);
							}}
							>Issue Certificate
						</Button>
					</Table.Cell>
				</Table.Row>
			{/each}
		</Table.Body>
	</Table.Root>
</div>
